### ISSUE TITLE
AsaLaunch.sh not available in the latest releases

### ISSUE THREAD

**Issue by yitam** [microsoft/AttackSurfaceAnalyzer#328]
**Describe the bug**
AsaLaunch.sh not available in the latest release

**To Reproduce**
Download the tarballs for Linux or macOS from several v2.1 releases 

**Expected behavior**
Expect to find AsaLaunch.sh as described in WIKI

**Screenshots**
![image](https://user-images.githubusercontent.com/21340756/71013563-bf560600-20a5-11ea-887b-adda37664c54.png)

**System Configuration (please complete the following information):**
Ubuntu 18.04 or macOS Catalina

Should I download v2.0 instead?

**Comment by gfs** [comment]
Sorry about that.  I'll check the build script to see why that might be happening.

For now, please run `res/Asa` directly.  `AsaLaunch.sh` is just a shortcut to run `res/Asa`.

**Comment by yitam** [comment]
hi @gfs I did try your suggestion before creating this issue, but it seems taking forever...

**Comment by scovetta** [comment]
Does it look like it's doing something, or stalled? If you run `./Asa --help` or `res/Asa --help` does it show usage information?

**Comment by yitam** [comment]
Do you mean when I run `res/Asa` and I should run `res/Asa --help` in another terminal?

**Comment by gfs** [comment]
When you say it's taking forever what do you mean in particular is happening? How long have you been waiting?

What command are you running?

What output do you receive so far?

If you run ASA --help in another window do you get the help output?

What OS are you running on?

-------- Original Message --------

**Comment by yitam** [comment]
hi @gfs I successfully ran v2.0 back in July in Ubuntu 18.04. This is the same platform I'm running v2.1
No problem with `ASA --help`

Would this screenshot answer your question? I downloaded the latest tarball and started running ASA more than 10 minutes ago:

![image](https://user-images.githubusercontent.com/21340756/71025003-04d0fe00-20bb-11ea-8904-11259af02652.png)

**Comment by gfs** [comment]
10 minutes for the file collector isn't outlandish. If it still hasn't finished that's an issue. Are you still having trouble?

-------- Original Message --------

**Comment by yitam** [comment]
yes, I quit after waiting for an hour...

**Comment by gfs** [comment]
Sorry you're still having trouble.

I'll set up an Ubuntu image and check it out.

-------- Original Message --------

**Comment by yitam** [comment]
FYI, this is captured today from Mojave today. 
At least it didn't stall... 

![image](https://user-images.githubusercontent.com/21340756/71108496-14fae300-2178-11ea-8a5d-04187eef1930.png)

**Comment by gfs** [comment]
Thanks for the report. I should have a fix this week.

-------- Original Message --------

**Comment by gfs** [comment]
I have a fix available for this crash.  The new build is running in the pipeline now.  

I found a new issue on Mac OS where the File Collector is not completing (#331), it's unclear what is causing that at this time.

**Comment by yitam** [comment]
Just downloaded 2.1.46 and it still appears to be stalling in Ubuntu 18.04 (nothing happens for 20 minutes or so). Should I revert to using v2.0?
